import type { Action } from '../types/game'

export const ACTIONS: Action[] = [
  {
    id: 'dsa',
    name: 'Practice DSA',
    description: 'Problem-solving. Slowly, then suddenly.',
    icon: 'code',
    cost: 1,
    effects: { dsa: 6, energy: -12, wellbeing: -3 },
    lines: [
      'Six problems. Still alive.',
      "Good. That's one problem off the list.",
      'You understood two-pointers. You will forget by Thursday.',
      'Solved a Medium on the first try. Nobody saw it.',
      'Dynamic programming: understood for exactly nine minutes.',
    ],
  },
  {
    id: 'study',
    name: 'Study',
    description: 'Semester subjects. The ones "that will come in placements."',
    icon: 'book-open',
    cost: 1,
    effects: { cgpa: 1.7, energy: -10, wellbeing: -3 },
    lines: [
      'Forty slides. Six understood. Standard ratio.',
      'Your notes are now better than the textbook. Marginally.',
      'The professor said this will come in placements. It will not.',
      'Studied. Nothing happened. That is how CGPA works.',
    ],
  },
  {
    id: 'project',
    name: 'Build project',
    description: 'Something for the resume that actually runs.',
    icon: 'hammer',
    cost: 1,
    effects: { projects: 5, energy: -12 },
    reveals: ['projects'],
    lines: [
      'Fixed a bug by deleting the feature. Shipped.',
      'The README has badges now. Practically production.',
      'Two hours on the name. Twenty minutes on the code.',
      'It works on your machine. That is a milestone.',
    ],
  },
  {
    id: 'sleep',
    name: 'Sleep',
    description: 'Real sleep. Not the phone-in-hand kind.',
    icon: 'moon',
    cost: 1,
    effects: { sleep: 20, energy: 15, wellbeing: 8 },
    lines: ['Finally.', 'Eight hours. A personal record this semester.', 'Woke up unsure what day it was. Good sign.'],
  },
  {
    id: 'mock',
    name: 'Mock interview',
    description: 'Tell me about yourself. Again.',
    icon: 'mic',
    cost: 1,
    effects: { interview: 5, energy: -10, wellbeing: -4 },
    reveals: ['interview'],
    lines: [
      'Said "great question" four times. Answered one.',
      'Explained a linked list using biryani. It almost worked.',
      'Better than last time. Last time was very bad.',
    ],
  },
  {
    id: 'resume',
    name: 'Fix resume',
    description: 'Turn "made a website" into something a recruiter reads.',
    icon: 'file-text',
    cost: 1,
    effects: { resume: 7, energy: -4 },
    reveals: ['resume'],
    lines: [
      'Removed the tenth-standard percentage. Growth.',
      '"Led a team" now describes a group project you did alone.',
      'Changed the font. Somehow it is thirty percent better.',
    ],
  },
  {
    id: 'network',
    name: 'Network',
    description: 'Message seniors. Hope they remember your face.',
    icon: 'users',
    cost: 1,
    effects: { networking: 5, luck: 2, energy: -4 },
    reveals: ['networking'],
    lines: [
      'Nine seniors messaged. One replied "ok".',
      'Attended a webinar with the camera off. Networking, technically.',
      'A senior remembered you. Unfortunately, from the attendance sheet.',
    ],
  },
  {
    id: 'chill',
    name: 'Go out',
    description: 'Friends, canteen, nothing productive.',
    icon: 'coffee',
    cost: 1,
    effects: { wellbeing: 15, energy: 5, sleep: 5 },
    lines: [
      'Discussed placements for three hours. Prepared: zero.',
      'Nobody mentioned DSA for a full evening. Healing.',
      'Your friend got placed. You are happy for him. Obviously.',
    ],
  },
  {
    id: 'college',
    name: 'Attend class',
    description: 'Attendance is a social construct. Until it is not.',
    icon: 'graduation-cap',
    cost: 1,
    effects: { cgpa: 0.6, energy: -6, motivation: 1 },
    lines: [
      'The professor looked surprised to see you.',
      'Marked attendance for three friends. Leadership.',
      'Class was cancelled after you reached. Naturally.',
    ],
  },
  {
    id: 'apply',
    name: 'Apply off-campus',
    description: 'Portals, forms, the same details twelve times.',
    icon: 'send',
    cost: 1,
    effects: { applications: 3, energy: -5 },
    reveals: ['applications'],
    lines: [
      'Twelve forms. One upload each. Zero replies, for now.',
      '"Easy Apply" continues to be a lie.',
      'Cover letter says passionate. You are mostly tired.',
    ],
  },
  {
    id: 'coffee',
    name: 'Coffee',
    description: 'Borrow energy from tonight.',
    icon: 'cup-soda',
    cost: 0,
    maxPerDay: 2,
    effects: { energy: 12, sleep: -8 },
    lines: ['Personality restored.', 'Second cup. Hands slightly unreliable now.'],
  },
  {
    id: 'rest',
    name: 'Write off the day',
    description: 'Do nothing on purpose. Uses all three actions.',
    icon: 'sofa',
    cost: 3,
    effects: { energy: 30, sleep: 15, wellbeing: 18, dsa: -1, motivation: -3 },
    lines: ['One more episode did, in fact, hurt.', 'Did nothing. It was everything.', 'Two hundred unread messages. Not today.'],
  },
]

export const ACTION_MAP: Record<string, Action> = Object.fromEntries(ACTIONS.map((a) => [a.id, a]))
