import type { GameEvent } from '../types/game'

export const EVENTS: GameEvent[] = [
  // ----- common -----
  {
    id: 'surprise_viva',
    title: 'Surprise viva',
    body: 'Your professor walks into the classroom.',
    quote: 'Keep your notebooks aside.',
    rarity: 'common',
    effects: { cgpa: -1, energy: -8, wellbeing: -5 },
    tags: ['negative', 'breakdown'],
  },
  {
    id: 'group_messages',
    title: '87 unread messages',
    body: 'The placement group has found a new company. Nobody knows the package. Everybody is applying.',
    rarity: 'common',
    effects: { applications: 2, wellbeing: -2 },
    reveals: ['applications'],
  },
  {
    id: 'maggi',
    title: 'Maggi at 1 AM',
    body: 'Two-minute noodles. Twenty-five-minute conversation. Nothing was solved and everything felt better.',
    rarity: 'common',
    effects: { wellbeing: 8, energy: 3 },
    tags: ['positive'],
  },
  {
    id: 'project_broke',
    title: 'The demo broke',
    body: "You don't have a job yet. Somehow there is already a production bug. The demo is tomorrow.",
    rarity: 'common',
    effects: { wellbeing: -3, projects: 1 },
    condition: { min: { projects: 15 } },
  },
  {
    id: 'linkedin_post',
    title: 'LinkedIn',
    body: 'Someone from your batch announced a 24 LPA offer.',
    quote: 'Grateful 🙏',
    rarity: 'common',
    effects: { wellbeing: -8, motivation: 5 },
    tags: ['linkedin', 'negative'],
  },
  {
    id: 'canteen_closed',
    title: 'Canteen closed',
    body: 'You walked all the way. Shutter down. "Closed for inventory." It is samosas.',
    rarity: 'common',
    effects: { energy: -5, wellbeing: -3 },
    tags: ['negative'],
  },
  {
    id: 'wifi_down',
    title: 'Hostel Wi-Fi',
    body: 'Down. During a contest. The submit button and the Wi-Fi have chosen violence together.',
    rarity: 'common',
    effects: { dsa: -1, wellbeing: -4, motivation: -2 },
    tags: ['negative'],
  },
  {
    id: 'senior_advice',
    title: 'A senior drops by',
    body: 'A placed senior explains everything in one sentence.',
    quote: 'Just do the sheet and revise OOPs, bro.',
    rarity: 'common',
    effects: { dsa: 2, motivation: 4, interview: 1 },
    tags: ['positive'],
  },
  {
    id: 'assignment',
    title: 'Assignment due tonight',
    body: 'Somebody in the group: "Guys, assignment is due at 11:59?" It is 11:12.',
    rarity: 'common',
    effects: { cgpa: 1, energy: -10, sleep: -8 },
  },
  {
    id: 'holiday',
    title: 'Surprise holiday',
    body: 'College is closed for a reason nobody understands. Nobody asks. Nobody wants to jinx it.',
    rarity: 'common',
    effects: { energy: 8, sleep: 8, wellbeing: 6 },
    tags: ['positive'],
  },
  {
    id: 'tapri',
    title: 'Tapri philosophy',
    body: 'Chai turned into a two-hour debate about whether CGPA matters. Conclusion: nobody knows.',
    rarity: 'common',
    effects: { wellbeing: 6, energy: -2, networking: 1 },
  },
  // ----- uncommon -----
  {
    id: 'three_am',
    title: '3 AM motivation',
    body: 'You suddenly believe you can become a software engineer by tomorrow. Fourteen tabs open. Fourteen tabs closed.',
    rarity: 'uncommon',
    effects: { motivation: 10, sleep: -15, dsa: 2 },
  },
  {
    id: 'streak',
    title: 'Seven-day streak',
    body: 'You committed code every day this week. Three commits were "fix typo". They count.',
    rarity: 'uncommon',
    effects: { projects: 3, motivation: 5 },
    tags: ['positive'],
    reveals: ['projects'],
  },
  {
    id: 'rejection_mail',
    title: 'Not this one',
    body: 'An email arrives.',
    quote: 'Unfortunately, we have decided to move forward with other candidates.',
    rarity: 'uncommon',
    effects: { wellbeing: -7, motivation: 2 },
    tags: ['rejection', 'negative'],
    condition: { min: { applications: 5 } },
  },
  {
    id: 'party',
    title: 'Everyone is going',
    body: 'Your friend is at the door. There is a party. Your DSA sheet is on the desk, watching.',
    rarity: 'uncommon',
    choices: [
      { label: 'Go. I deserve this.', effects: { wellbeing: 15, energy: -10, sleep: -10, networking: 2 }, line: 'Danced badly. Laughed loudly. Regret is scheduled for tomorrow.' },
      { label: 'Stay. The sheet is watching.', effects: { dsa: 5, wellbeing: -5, energy: -8 }, line: 'Three problems solved with bass coming through the wall. Character.' },
      { label: 'One hour, then back.', effects: { wellbeing: 7, energy: -4, sleep: -3 }, line: 'One hour became two. Still a win by hostel standards.' },
    ],
  },
  {
    id: 'lab_partner',
    title: 'Lab partner missing',
    body: 'A "family emergency" for the fourth time this month. The lab file is now your solo project.',
    rarity: 'uncommon',
    effects: { cgpa: 0.8, energy: -8, wellbeing: -4 },
  },
  {
    id: 'placement_cell',
    title: 'Placement cell mail',
    body: '"Students with less than 75% attendance will not be eligible." You check. You sweat.',
    rarity: 'uncommon',
    conditional: { key: 'motivation', threshold: 40, above: { wellbeing: 3, motivation: 2 }, below: { wellbeing: -8, motivation: 4 } },
  },
  {
    id: 'mom_call',
    title: 'Mom called',
    body: 'Sharma ji ka beta got placed. Thirty lakhs, apparently. You have never met Sharma ji.',
    rarity: 'uncommon',
    choices: [
      { label: '"Haan mummy, I am also preparing."', effects: { motivation: 6, wellbeing: -3 }, line: 'A small lie. Then you actually opened LeetCode. Sharma ji wins again.' },
      { label: 'Ask what she cooked instead.', effects: { wellbeing: 8, energy: 2 }, line: 'Twenty minutes about rajma. Placements forgotten. Peace.' },
    ],
  },
  {
    id: 'midsem',
    title: 'Mid-sem schedule released',
    body: 'Exams start in four days. Six subjects. You have opened zero of them.',
    rarity: 'uncommon',
    choices: [
      { label: 'All-nighters. CGPA first.', effects: { cgpa: 2.5, sleep: -18, energy: -12, wellbeing: -5 }, line: 'You know the syllabus better than the professor now. You also cannot feel your face.' },
      { label: 'Revise, then sleep.', effects: { cgpa: 1.2, sleep: -4, energy: -6 }, line: 'Respectable effort. Respectable outcome. Respectably tired.' },
      { label: 'Placements matter more.', effects: { dsa: 5, cgpa: -1.5, wellbeing: -3 }, line: 'Marks dipped. Recursion improved. Trade accepted.' },
    ],
  },
  {
    id: 'oa_tomorrow',
    title: 'Online assessment tomorrow',
    body: 'The mail came at 9 PM. The test is at 10 AM. Syllabus: everything.',
    rarity: 'uncommon',
    condition: { minDay: 25 },
    tags: ['opportunity'],
    choices: [
      { label: 'Cram all night.', effects: { dsa: 4, sleep: -15, energy: -10, interview: 2 }, line: 'Two of three solved. The third was a graph. It is always a graph.' },
      { label: 'Sleep. Trust the prep.', effects: { sleep: 6, luck: 3, interview: 2 }, line: 'Woke up fresh. Solved what you knew. Guessed the rest with confidence.' },
    ],
  },
  // ----- rare -----
  {
    id: 'friend_referral',
    title: 'Your friend texted',
    body: '',
    quote: 'Bro. Referral. Send resume. Now.',
    rarity: 'rare',
    tags: ['referral', 'opportunity', 'positive'],
    reveals: ['networking', 'applications'],
    choices: [
      { label: 'Send it.', effects: { networking: 10, applications: 5, luck: 5 }, line: 'Sent in eleven seconds. Okay. That is interesting.' },
      { label: 'Ask for details first.', effects: { networking: 6, applications: 3, interview: 2 }, line: 'Turns out it is a good role. You send it, slightly better prepared.' },
      { label: 'Ignore. Busy.', effects: { energy: 3, motivation: -4 }, line: 'Your friend sends a thumbs-down. That was probably a mistake.' },
    ],
  },
  {
    id: 'recruiter',
    title: 'A recruiter replied',
    body: 'A real human replied to your cold message. You read it nine times before answering.',
    rarity: 'rare',
    effects: { applications: 1, interview: 3, motivation: 5 },
    tags: ['opportunity', 'positive'],
  },
  {
    id: 'shortlisted_mail',
    title: 'Shortlisted',
    body: 'Your resume made it past the filter. The "architected scalable platform" line worked.',
    rarity: 'rare',
    condition: { minDay: 35, min: { resume: 30 } },
    effects: { interview: 4, motivation: 6, wellbeing: 5 },
    tags: ['opportunity', 'positive'],
  },
  {
    id: 'hackathon',
    title: 'Hackathon weekend',
    body: 'Your friend registered your team without asking. Theme: "AI for Good". Thirty-six hours, one working laptop.',
    rarity: 'rare',
    choices: [
      { label: 'All in.', effects: { projects: 10, networking: 4, sleep: -20, energy: -18, wellbeing: 4 }, line: 'The demo worked exactly once, during the pitch. Legendary timing.' },
      { label: 'Contribute, but sleep.', effects: { projects: 5, networking: 2, energy: -6 }, line: 'You made the README and the logo. Your team says you "did branding".' },
    ],
    reveals: ['projects'],
  },
  {
    id: 'breakdown',
    title: 'A small breakdown',
    body: 'Hostel bathroom. Five minutes. Then you washed your face and opened the sheet again.',
    rarity: 'rare',
    condition: { max: { wellbeing: 35 } },
    effects: { wellbeing: 5, motivation: 4, energy: -5 },
    tags: ['breakdown'],
  },
  {
    id: 'rejected_after_oa',
    title: 'Rejected after the OA',
    body: 'You solved all three. Still rejected. The universe is a hash collision.',
    rarity: 'rare',
    condition: { minDay: 40 },
    effects: { wellbeing: -9, motivation: 3, luck: 2 },
    tags: ['rejection', 'negative', 'breakdown'],
  },
  // ----- epic -----
  {
    id: 'mentor',
    title: 'A senior offers to help',
    body: 'Someone at a big company says: send me your resume, I will review it and refer you.',
    rarity: 'epic',
    effects: { resume: 10, networking: 8, interview: 4, luck: 4 },
    tags: ['referral', 'opportunity', 'positive'],
    reveals: ['resume', 'networking'],
  },
  {
    id: 'viral_repo',
    title: 'Your repo got shared',
    body: 'Four hundred stars overnight. Two of them are your alt accounts.',
    rarity: 'epic',
    condition: { min: { projects: 25 } },
    effects: { projects: 8, networking: 6, wellbeing: 10 },
    tags: ['positive'],
  },
  {
    id: 'paper_hint',
    title: 'The professor hinted',
    body: '"Focus on chapters three and five." The paper was chapters three and five. Attendance paid off.',
    rarity: 'epic',
    condition: { min: { motivation: 30 } },
    effects: { cgpa: 3, wellbeing: 6 },
    tags: ['positive'],
  },
  {
    id: 'burnout',
    title: 'Burnout',
    body: 'You stared at a for-loop for forty minutes. Your body has filed a formal complaint.',
    rarity: 'epic',
    condition: { max: { energy: 15 } },
    tags: ['breakdown'],
    choices: [
      { label: 'Take the day.', effects: { energy: 25, sleep: 15, wellbeing: 12, motivation: -2 }, line: 'Fourteen hours of sleep. You are a person again. Roughly.' },
      { label: 'Coffee and push through.', effects: { dsa: 3, energy: -5, sleep: -10, wellbeing: -8 }, line: 'Fourth coffee. You can hear colours. One problem solved.' },
    ],
  },
  // ----- legendary -----
  {
    id: 'dream_referral',
    title: 'A stranger referred you',
    body: 'Someone from a comment section referred you to your dream company. The algorithm did one good thing.',
    rarity: 'legendary',
    effects: { networking: 15, applications: 8, luck: 10, interview: 5 },
    tags: ['referral', 'opportunity', 'positive', 'linkedin'],
    reveals: ['networking', 'applications'],
  },
  {
    id: 'topper_notes',
    title: 'The topper shared notes',
    body: 'Colour-coded. Indexed. Your CGPA is quietly weeping.',
    rarity: 'legendary',
    effects: { cgpa: 4, energy: 5, wellbeing: 8, networking: 3 },
    tags: ['positive'],
  },
]

export const EVENT_MAP: Record<string, GameEvent> = Object.fromEntries(EVENTS.map((e) => [e.id, e]))
